result_handler:
  type: SOCKET
  socket:
    port: 60060
    host: 127.0.0.1

instances:
  - source:
      type: VIDEO_FILE # CAMERA
      data_folder: C:/_koray/test_data/
      file_path: iett_2.avi
      device: "iett_2"
      preview_show: True
    runners:
      - name: yolov5m - Object detection with 80 classes (Fast)
        type: yolov5m
        configuration: yolov5m.json
        class: Yolov5mRunner
        priority: 10
      - name: Cigarette Detector
        type: cigarette_detector
        configuration: cigarette_detector.json
        class: CigaretteDetectorRunner
        priority: 10

  - source:
      type: VIDEO_FILE # CAMERA
      data_folder: C:/_koray/test_data/
      file_path: iett_2.avi
      device: "iett_2_2"
      preview_show: True
    runners:
      - name: yolov5m - Object detection with 80 classes (Fast)
        type: yolov5m
        configuration: yolov5m.json
        class: Yolov5mRunner
        priority: 10
      - name: Person Counter
        type: personcounter
        configuration: person_counter.json
        class: person_counter_runner
        priority: 100
