#!/bin/sh
set -e

# Automatically added by dh_python3:
if which py3compile >/dev/null 2>&1; then
	py3compile -p python3-ndu-gate 
fi
if which pypy3compile >/dev/null 2>&1; then
	pypy3compile -p python3-ndu-gate  || true
fi

# End automatically added section
echo "Installing jsonschema"
sudo rm -rf /usr/lib/python3/dist-packages/jsonschema
CURRENT_USER=$USER
sudo pip3 install --upgrade jsonschema==3.1.1
sudo pip3 install --upgrade pyrsistent --progress-bar off -qqq || echo "OK"
sudo pip3 install --upgrade importlib --progress-bar off -qqq || echo "OK"
sudo pip3 install --upgrade importlib-metadata --progress-bar off -qqq || echo "OK"
#sudo cp -a -r -v /etc/ndu-gate/extensions /var/lib/ndu_gate/
sudo cp -a -r -v /etc/ndu-gate/runners /var/lib/ndu_gate/
#sudo rm -r -v /etc/ndu-gate/extensions
sudo rm -r -v /etc/ndu-gate/runners
sudo usermod -a -G dialout $CURRENT_USER
sudo usermod -a -G ndu_gate $CURRENT_USER
sudo chown ndu_gate:ndu_gate /var/log/ndu-gate/ -R
sudo chown ndu_gate:ndu_gate /var/lib/ndu_gate/ -R
sudo chown ndu_gate:ndu_gate /etc/ndu-gate/ -R
sudo sed -i 's/\.\/logs/\/var\/log\/ndu-gate/g' /etc/ndu-gate/config/logs.conf >> /etc/ndu-gate/config/logs.conf
sudo sed -i 's/\.\/logs/\/var\/log\/ndu-gate/g' /etc/ndu-gate/config/logs_macosx.conf >> /etc/ndu-gate/config/logs_macosx.conf
echo "Kurulum tamamlandı"
echo "NDU-Gate kamera servisi başlatılıyor..."
sudo pidof systemd && sudo systemctl enable ndu-gate || echo "Systemctl not found"
#echo "Daemon starting..."
sudo pidof systemd && sudo systemctl start ndu-gate || echo
echo -e "\e[96mNDU-Gate Camera Service kurulumu tamamlandi. opencv, tensorflow, torch vs. gibi kütüphaneleri kurmayı unutma \e[93m\e[5m:P\e[25m\e[39m"