#!/bin/sh
set -e

echo "Installing directory for configs..."
sudo mkdir /etc/ndu-gate || echo
sudo adduser --system --gecos "NDU-Gate Camera Service" --disabled-password --group --home /var/lib/ndu_gate ndu_gate || echo "User exists"
sudo mkdir /var/lib/ndu_gate/extensions || echo
sudo mkdir /var/lib/ndu_gate/runners || echo
